R_SFE_th
R_SFE_thd
R_SFE_thdd
R_SFE_u
R_SFE_load

R_SAA_th
R_SAA_thd
R_SAA_thdd
R_SAA_u
R_SAA_load

R_HR_th
R_HR_thd
R_HR_thdd
R_HR_u
R_HR_load

R_EB_th
R_EB_thd
R_EB_thdd
R_EB_u
R_EB_load

R_WR_th
R_WR_thd
R_WR_thdd
R_WR_u
R_WR_load

R_WFE_th
R_WFE_thd
R_WFE_thdd
R_WFE_u
R_WFE_load

R_WAA_th
R_WAA_thd
R_WAA_thdd
R_WAA_u
R_WAA_load

R_TL_th
R_TL_thd
R_TL_thdd
R_TL_u
R_TL_load

R_TV_th
R_TV_thd
R_TV_thdd
R_TV_u
R_TV_load

R_FAA_th
R_FAA_thd
R_FAA_thdd
R_FAA_u
R_FAA_load
